# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='name',
            field=models.TextField(default='tbd'),
        ),
    ]
