# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0002_character_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Mensch')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='type',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='dsa_starter.Race'),
            preserve_default=False,
        ),
    ]
