# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0004_auto_20170418_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='charisma',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='culture',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='character',
            name='fingerfertigkeit',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='character',
            name='gewandheit',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='intuition',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='klugheit',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='koerperkraft',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='konstitution',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='mut',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='size',
            field=models.SmallIntegerField(default=175),
        ),
        migrations.AddField(
            model_name='character',
            name='social_rank',
            field=models.SmallIntegerField(default=0),
        ),
    ]
