# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0005_auto_20170418_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='D', max_length=1)),
                ('cost_per_increase', models.SmallIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SkillType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behinderung', models.CharField(default='', max_length=4)),
                ('skill_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsa_starter.SkillGroup')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='attack_basis',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='experience_used',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='ini_basis',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='magieresistenz',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='parade_basis',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skills',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsa_starter.SkillType'),
        ),
    ]
