# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0006_auto_20170418_1746'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
        migrations.AddField(
            model_name='skillgroup',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
