# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0008_auto_20170418_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='dice1',
            field=models.CharField(choices=[('GE', 'Gewandheit'), ('KK', 'K\xf6rperkraft'), ('KO', 'Konstitution'), ('KL', 'Klugheit'), ('MU', 'Mut'), ('CH', 'Charisma'), ('FF', 'Fingerfertigkeit'), ('IN', 'Intuition')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='skill',
            name='dice2',
            field=models.CharField(choices=[('GE', 'Gewandheit'), ('KK', 'K\xf6rperkraft'), ('KO', 'Konstitution'), ('KL', 'Klugheit'), ('MU', 'Mut'), ('CH', 'Charisma'), ('FF', 'Fingerfertigkeit'), ('IN', 'Intuition')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='skill',
            name='dice3',
            field=models.CharField(choices=[('GE', 'Gewandheit'), ('KK', 'K\xf6rperkraft'), ('KO', 'Konstitution'), ('KL', 'Klugheit'), ('MU', 'Mut'), ('CH', 'Charisma'), ('FF', 'Fingerfertigkeit'), ('IN', 'Intuition')], default='', max_length=2),
        ),
    ]
