# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0009_auto_20170418_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(default=0)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsa_starter.Skill')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='skills',
            field=models.ManyToManyField(to='dsa_starter.ActualSkill'),
        ),
    ]
