# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0010_auto_20170418_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='skills',
        ),
    ]
