# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0011_remove_character_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualskill',
            name='character',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dsa_starter.Character'),
        ),
    ]
