# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0013_auto_20170424_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
