# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0014_auto_20170426_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillgroup',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='skilltype',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
