# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0016_character_life_lost'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='my_fav_path'),
        ),
    ]
