# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0018_character_avatar_small'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='basis',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
