# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-19 11:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0019_skill_basis'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeaponSkillDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dsa_starter.Character')),
                ('skill', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dsa_starter.Skill')),
            ],
        ),
    ]
