# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-03 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0022_auto_20180606_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FightCharactParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dsa_starter.Character')),
                ('fight', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dsa_starter.Fight')),
            ],
        ),
    ]
