# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-27 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0026_auto_20180903_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hit_dices', models.SmallIntegerField(default=1)),
                ('hit_add_points', models.SmallIntegerField(default=2)),
            ],
        ),
        migrations.AddField(
            model_name='fightcharacterparticipation',
            name='position',
            field=models.CharField(choices=[('B', 'Back'), ('F', 'Front'), ('VF', 'Very Front')], default='B', max_length=1),
        ),
    ]
