# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-27 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0027_auto_20181127_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
