# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-26 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0027_auto_20181126_1045'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdventureImages',
            new_name='AdventureImage',
        ),
    ]
