# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-26 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0028_auto_20181126_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
