# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-27 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0028_auto_20181127_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterHasWeapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsa_starter.Character')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsa_starter.Weapon')),
            ],
        ),
    ]
