# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-26 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0029_adventure_isactive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adventureimage',
            old_name='avatar',
            new_name='url',
        ),
    ]
