# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-27 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0029_characterhasweapon'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='skill_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dsa_starter.Skill'),
            preserve_default=False,
        ),
    ]
