# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 07:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0030_weapon_skill_type'),
        ('dsa_starter', '0030_auto_20181126_1203'),
    ]

    operations = [
    ]
