# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-29 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0031_merge_20181128_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adventureimage',
            name='url',
        ),
        migrations.AddField(
            model_name='adventureimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='character',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='character',
            name='avatar_small',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
