# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-15 05:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0032_auto_20181129_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonPlayerCharacterHasWeapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsa_starter.NonPlayerCharacter')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsa_starter.Weapon')),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200)),
                ('dice1', models.CharField(choices=[('GE', 'Gewandheit'), ('KK', 'Körperkraft'), ('KO', 'Konstitution'), ('KL', 'Klugheit'), ('MU', 'Mut'), ('CH', 'Charisma'), ('FF', 'Fingerfertigkeit'), ('IN', 'Intuition')], default='', max_length=2)),
                ('dice2', models.CharField(choices=[('GE', 'Gewandheit'), ('KK', 'Körperkraft'), ('KO', 'Konstitution'), ('KL', 'Klugheit'), ('MU', 'Mut'), ('CH', 'Charisma'), ('FF', 'Fingerfertigkeit'), ('IN', 'Intuition')], default='', max_length=2)),
                ('dice3', models.CharField(choices=[('GE', 'Gewandheit'), ('KK', 'Körperkraft'), ('KO', 'Konstitution'), ('KL', 'Klugheit'), ('MU', 'Mut'), ('CH', 'Charisma'), ('FF', 'Fingerfertigkeit'), ('IN', 'Intuition')], default='', max_length=2)),
                ('basis', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SpellType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='spell',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsa_starter.SpellType'),
        ),
    ]
