# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-15 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0033_auto_20190715_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='herotype',
            name='knowsMagic',
            field=models.BooleanField(default=False),
        ),
    ]
