# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-15 05:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0034_herotype_knowsmagic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualSpellSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(default=0)),
                ('character', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dsa_starter.Character')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsa_starter.Spell')),
            ],
        ),
    ]
