# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-20 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0035_actualspellskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('nameLong', models.TextField()),
            ],
        ),
    ]
