# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-20 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0036_attribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='id',
            field=models.CharField(default='', max_length=200, primary_key=True, serialize=False),
        ),
    ]
