# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-20 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0038_auto_20190720_1531'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attribute',
        ),
    ]
