# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-25 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0039_delete_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='magic_energy',
            field=models.SmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='character',
            name='magic_energy_lost',
            field=models.SmallIntegerField(default=0),
        ),
    ]
