# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-30 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0040_auto_20190725_0805'),
        ('dsa_starter', '0040_auto_20190922_1824'),
    ]

    operations = [
    ]
