# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-30 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0041_merge_20191230_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='armor',
            field=models.SmallIntegerField(default=1),
        ),
    ]
