# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-19 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0043_inventoryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='money_dukaten',
            field=models.SmallIntegerField(default=0),
        ),
    ]
