# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-23 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0044_character_money_dukaten'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='money_heller',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='money_kreuzer',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='money_silbertaler',
            field=models.SmallIntegerField(default=0),
        ),
    ]
