# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-23 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0045_auto_20200523_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='unit',
            field=models.CharField(choices=[('SK', 'Schank'), ('ST', 'Stein'), ('UZ', 'Unze'), ('MS', 'Maß'), ('FX', 'Flux')], default='SK', max_length=2),
        ),
    ]
