# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-24 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0046_inventoryitem_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('ruestungs_schutz', models.SmallIntegerField(default=1)),
                ('behinderung', models.SmallIntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterHasArmor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('armor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsa_starter.Armor')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsa_starter.Character')),
            ],
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit',
            field=models.CharField(choices=[('SK', 'Stück'), ('ST', 'Stein'), ('UZ', 'Unze'), ('SR', 'Skrupel'), ('MS', 'Maß'), ('SN', 'Schank'), ('FX', 'Flux')], default='SK', max_length=2),
        ),
    ]
