# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-25 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0047_auto_20200524_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='abenteuer_punkte',
            field=models.SmallIntegerField(default=0),
        ),
    ]
