# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-25 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0048_character_abenteuer_punkte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='abenteuer_punkte',
        ),
    ]
