# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-01 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0049_remove_character_abenteuer_punkte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ascensions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.SmallIntegerField(default=1)),
                ('cost_a', models.SmallIntegerField(default=1)),
                ('cost_b', models.SmallIntegerField(default=1)),
                ('cost_c', models.SmallIntegerField(default=1)),
                ('cost_d', models.SmallIntegerField(default=1)),
                ('cost_e', models.SmallIntegerField(default=1)),
                ('cost_f', models.SmallIntegerField(default=1)),
                ('cost_g', models.SmallIntegerField(default=1)),
                ('cost_h', models.SmallIntegerField(default=1)),
            ],
        ),
    ]
