# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-30 15:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0041_merge_20200808_1250'),
        ('dsa_starter', '0050_ascensions'),
    ]

    operations = [
    ]
