# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-30 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0051_merge_20210130_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='charisma',
            new_name='CH',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='fingerfertigkeit',
            new_name='FF',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='gewandheit',
            new_name='GE',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='intuition',
            new_name='IN',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='klugheit',
            new_name='KL',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='koerperkraft',
            new_name='KK',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='konstitution',
            new_name='KO',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='mut',
            new_name='MU',
        ),
    ]
