# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-02-05 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0052_auto_20210130_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='hit_extra_from_kk',
            field=models.SmallIntegerField(default=14),
        ),
    ]
