# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-02-13 01:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0053_weapon_hit_extra_from_kk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weapon',
            old_name='skill_type',
            new_name='skill',
        ),
    ]
