# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-02-14 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0054_auto_20210213_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='weaponSkill',
            field=models.BooleanField(default=False),
        ),
    ]
