# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-03-04 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0055_skill_weaponskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='weight',
            field=models.SmallIntegerField(default=1),
        ),
    ]
