# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-01-02 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0056_inventoryitem_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='ini_basis',
        ),
        migrations.AddField(
            model_name='character',
            name='hair_color',
            field=models.CharField(default='', max_length=200),
        ),
    ]
