# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-01-02 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0057_auto_20220102_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='eye_color',
            field=models.CharField(default='', max_length=200),
        ),
    ]
