# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-01-02 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0058_character_eye_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='weight',
            field=models.SmallIntegerField(default=70),
        ),
    ]
