# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-11-09 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0059_character_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdventureCharacters',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(default='tbd', max_length=200)),
                ('sequenceInAdventure', models.SmallIntegerField(default=0)),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsa_starter.Adventure')),
            ],
        ),
        migrations.CreateModel(
            name='AdventureLocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='tbd', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsa_starter.Adventure')),
            ],
        ),
        migrations.AddField(
            model_name='adventureimage',
            name='sequenceInAdventure',
            field=models.SmallIntegerField(default=0),
        ),
    ]
