# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-11-10 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0060_auto_20221109_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventureimage',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
