# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-11-10 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0062_auto_20221110_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventurecharacter',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adventurelocation',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
