# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-11-11 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0063_auto_20221110_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdventureSection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sequenceInAdventure', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='adventureimage',
            old_name='sequenceInAdventure',
            new_name='sequence',
        ),
        migrations.AddField(
            model_name='adventureimage',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dsa_starter.AdventureSection'),
            preserve_default=False,
        ),
    ]
