# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-11-11 21:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0064_auto_20221111_2215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adventureimage',
            old_name='sequence',
            new_name='sequenceInAdventure',
        ),
    ]
