# Generated by Django 3.2.19 on 2023-05-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0066_remove_adventureimage_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPCTypes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='tbd', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='isHero',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='fightcharacterparticipation',
            name='position',
            field=models.CharField(choices=[('B', 'Back'), ('F', 'Front'), ('VF', 'Very Front')], default='B', max_length=2),
        ),
    ]
