# Generated by Django 3.2.19 on 2023-05-27 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0067_auto_20230527_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventurecharacter',
            name='character',
            field=models.ForeignKey(default='5', on_delete=django.db.models.deletion.DO_NOTHING, to='dsa_starter.character'),
        ),
    ]
