# Generated by Django 3.2.19 on 2023-05-27 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0068_adventurecharacter_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventurecharacter',
            name='character',
            field=models.ForeignKey(blank=True, default='5', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dsa_starter.character'),
        ),
    ]
