# Generated by Django 3.2.19 on 2023-05-28 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0069_alter_adventurecharacter_character'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NPCTypes',
            new_name='NPCType',
        ),
    ]
