# Generated by Django 3.2.19 on 2023-05-28 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0070_rename_npctypes_npctype'),
    ]

    operations = [
        migrations.AddField(
            model_name='npctype',
            name='attack',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='npctype',
            name='parade',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='npctype',
            name='race',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dsa_starter.race'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='npctype',
            name='weapon_1_damage',
            field=models.CharField(default='1W+4', max_length=8),
        ),
        migrations.AddField(
            model_name='npctype',
            name='weapon_1_name',
            field=models.CharField(default='tbd', max_length=200),
        ),
        migrations.AddField(
            model_name='npctype',
            name='weapon_2_damage',
            field=models.CharField(default='1W+4', max_length=8),
        ),
        migrations.AddField(
            model_name='npctype',
            name='weapon_2_name',
            field=models.CharField(default='tbd', max_length=200),
        ),
        migrations.AlterField(
            model_name='npctype',
            name='name',
            field=models.CharField(default='Söldner', max_length=200),
        ),
    ]
