# Generated by Django 3.2.19 on 2023-05-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0071_auto_20230528_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='npctype',
            name='initiative',
            field=models.SmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='npctype',
            name='knowsMagic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='npctype',
            name='life',
            field=models.SmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='npctype',
            name='magic_energy',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='npctype',
            name='ruestung',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='npctype',
            name='attack',
            field=models.SmallIntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='npctype',
            name='parade',
            field=models.SmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='npctype',
            name='weapon_1_name',
            field=models.CharField(default='Schwert', max_length=200),
        ),
        migrations.AlterField(
            model_name='npctype',
            name='weapon_2_damage',
            field=models.CharField(default='1W+1', max_length=8),
        ),
        migrations.AlterField(
            model_name='npctype',
            name='weapon_2_name',
            field=models.CharField(default='Dolch', max_length=200),
        ),
    ]
