# Generated by Django 3.2.19 on 2023-05-29 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0072_auto_20230528_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nonplayercharacter',
            name='avatar',
        ),
    ]
