# Generated by Django 3.2.19 on 2023-05-29 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0076_auto_20230529_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adventurecharacter',
            name='npc',
        ),
    ]
