# Generated by Django 3.2.19 on 2023-05-29 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0078_adventurecharacter_npc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adventurecharacter',
            name='image',
        ),
        migrations.RemoveField(
            model_name='adventurecharacter',
            name='name',
        ),
    ]
