# Generated by Django 3.2.19 on 2023-05-29 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0079_auto_20230529_0857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nonplayercharacterhasweapon',
            name='character',
        ),
        migrations.RemoveField(
            model_name='nonplayercharacterhasweapon',
            name='weapon',
        ),
        migrations.RemoveField(
            model_name='adventurecharacter',
            name='npc',
        ),
        migrations.DeleteModel(
            name='NonPlayerCharacter',
        ),
        migrations.DeleteModel(
            name='NonPlayerCharacterHasWeapon',
        ),
    ]
