# Generated by Django 3.2.19 on 2023-05-29 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0080_auto_20230529_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventurecharacter',
            name='character',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='dsa_starter.character'),
        ),
    ]
