# Generated by Django 3.2.19 on 2023-05-29 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0081_alter_adventurecharacter_character'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonPlayerCharacter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('avatar_small', models.ImageField(blank=True, null=True, upload_to='my_fav_path')),
                ('name', models.CharField(default='tbd', max_length=200)),
                ('initiative', models.SmallIntegerField(default=0)),
                ('attack', models.SmallIntegerField(default=0)),
                ('parade', models.SmallIntegerField(default=0)),
                ('hit_points', models.CharField(default='1W6+4', max_length=6)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsa_starter.race')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsa_starter.herotype')),
            ],
        ),
        migrations.AlterField(
            model_name='adventurecharacter',
            name='character',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dsa_starter.character'),
        ),
        migrations.CreateModel(
            name='NonPlayerCharacterHasWeapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsa_starter.nonplayercharacter')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsa_starter.weapon')),
            ],
        ),
        migrations.AddField(
            model_name='adventurecharacter',
            name='npc',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dsa_starter.nonplayercharacter'),
        ),
    ]
