# Generated by Django 3.2.19 on 2023-05-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0083_auto_20230529_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nonplayercharacter',
            name='avatar_small',
        ),
        migrations.RemoveField(
            model_name='nonplayercharacter',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='nonplayercharacter',
            name='hit_points',
        ),
        migrations.RemoveField(
            model_name='nonplayercharacter',
            name='type',
        ),
        migrations.AddField(
            model_name='nonplayercharacter',
            name='weapon_1_attack',
            field=models.SmallIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='nonplayercharacter',
            name='weapon_1_parade',
            field=models.SmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='nonplayercharacter',
            name='weapon_2_attack',
            field=models.SmallIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='nonplayercharacter',
            name='weapon_2_parade',
            field=models.SmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='nonplayercharacter',
            name='attack',
            field=models.SmallIntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='nonplayercharacter',
            name='name',
            field=models.CharField(default='Söldner', max_length=200),
        ),
        migrations.AlterField(
            model_name='nonplayercharacter',
            name='parade',
            field=models.SmallIntegerField(default=10),
        ),
    ]
