# Generated by Django 3.2.19 on 2023-05-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0084_auto_20230529_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonplayercharacter',
            name='avatar_small',
            field=models.ImageField(blank=True, null=True, upload_to='my_fav_path'),
        ),
    ]
