# Generated by Django 3.2.19 on 2023-06-11 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0086_fightcharacterparticipation_isgood'),
    ]

    operations = [
        migrations.CreateModel(
            name='FightParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isGood', models.BooleanField(default=True)),
                ('position', models.CharField(choices=[('B', 'Back'), ('F', 'Front'), ('VF', 'Very Front')], default='B', max_length=2)),
                ('character', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dsa_starter.character')),
                ('fight', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dsa_starter.fight')),
                ('npc', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dsa_starter.nonplayercharacter')),
            ],
        ),
        migrations.DeleteModel(
            name='FightCharacterParticipation',
        ),
    ]
