# Generated by Django 3.2.19 on 2023-06-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0087_auto_20230611_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='fightparticipation',
            name='calculatedInitiative',
            field=models.IntegerField(default=0),
        ),
    ]
