# Generated by Django 3.2.19 on 2023-06-13 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0089_fight_nextup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fightparticipation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
