# Generated by Django 3.2.19 on 2024-06-09 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_starter', '0092_rightssupport'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='complexity',
            field=models.ForeignKey(default='6', on_delete=django.db.models.deletion.CASCADE, to='dsa_starter.skillgroup'),
            preserve_default=False,
        ),
    ]
