branch-defaults:
  master:
    environment: dsa-server-dev
environment-defaults:
  dsa-server-dev:
    branch: null
    repository: null
global:
  application_name: dsa-server
  default_ec2_keyname: ec2-michel-dsa
  default_platform: Python 3.11 running on 64bit Amazon Linux 2023
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
